### ISSUE TITLE
dont complile on macbook pro

### ISSUE THREAD

**Issue by AnGen** [simonbs/SBSAnimoji#23]
high sierra
xcode last ver

very good project
dont use xcode earlier and have some problems

screen: https://yadi.sk/i/miFlt_wT3Q3AoK

do you have video how I could compile?

**Comment by slam2000** [comment]
I have the same problem on my 2017 MacBook. Anyone can help?

**Comment by DrJapan** [comment]
The problem here is that you're trying to run the project in the iPhone X simulator. As the simulator doesn't have the necessary hardware, you're going to get that error. (no sensors) You need to plugin your iPhone X, wait for Xcode to prepare your device for development, and then build/run on the device.
